version: '3'
services:
  nodejs:
    build:
      context:./frontend
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    networks:
      - app-network

  webserver:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - web-root:/var/www/html
      -./nginx-conf:/etc/nginx/conf.d
      -./api-spec.json:/usr/share/nginx/html/api-spec.json
    depends_on:
      - nodejs
    networks:
      - app-network

volumes:
  web-root:
    driver: local

networks:
  app-network:
    driver: bridge
