version: '2'

networks:
  todonet:

services:
  postgresdb:
    image: postgres
    networks:
      - todonet
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=matthias
      - POSTGRES_DB=mydb

  todobackend-springboot:
    image: maeddes/todobackend-springboot:v2404
    networks:
      - todonet
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - OTEL_EXPORTER_OTLP_ENDPOINT=otelcol:4317
      - OTEL_EXPORTER_OTLP_METRICS_ENDPOINT=otelcol:4317
      - OTEL_EXPORTER_OTLP_TRACES_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_METRICS_PROTOCOL=grpc
      - OTEL_RESOURCE_ATTRIBUTES=service.name=todobackend-springboot
      - OTEL_METRICS_EXPORTER=otlp,logging-otlp
      - OTEL_LOGS_EXPORTER=none
    depends_on:
      - postgresdb

  frontend:
    build:
      context: ./frontend  # Ensure this path is correct
      dockerfile: Dockerfile  # Ensure Dockerfile exists in the context path
      args:
        VUE_APP_BASE_URL: "http://todobackend-springboot:8080" # This points to the backend within the Docker network
    depends_on:
      - todobackend-springboot
    ports:
      - "3000:80"
    networks:
      - todonet
